# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('GroundID', models.IntegerField(primary_key=True, serialize=False)),
                ('GroundType', models.CharField(max_length=20)),
                ('PitchType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('MatchID', models.IntegerField(primary_key=True, serialize=False)),
                ('TeamID1', models.IntegerField()),
                ('TeamID2', models.IntegerField()),
                ('SeriesID', models.IntegerField()),
                ('GroundID', models.IntegerField()),
                ('MDate', models.DateField()),
                ('Umpire', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fours', models.IntegerField(null=True)),
                ('Sixes', models.IntegerField(null=True)),
                ('TotalRuns', models.IntegerField(null=True)),
                ('Catches', models.IntegerField(null=True)),
                ('Wickets', models.IntegerField(null=True)),
                ('Overs', models.IntegerField(null=True)),
                ('Type', models.CharField(max_length=5)),
                ('Strategy', models.CharField(max_length=10, null=True)),
                ('MatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Match')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('SeriesID', models.IntegerField(primary_key=True, serialize=False)),
                ('ManOfTheSeries', models.IntegerField()),
                ('GroundID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Ground')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamID', models.IntegerField(primary_key=True, serialize=False)),
                ('HostGroundID', models.IntegerField(null=True)),
                ('Coach', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='playerteam',
            name='TeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Team'),
        ),
    ]
